CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE run_status AS ENUM ('CREATED','PLANNING','WORKING','VERIFYING','REVIEWING','AWAITING_APPROVAL','DONE_CANDIDATE','FAILED','QUARANTINED');
CREATE TABLE missions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mission_id uuid NOT NULL REFERENCES missions(id), body text NOT NULL, acceptance_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requirement_id uuid NOT NULL REFERENCES requirements(id), title text NOT NULL, status text NOT NULL, repository text NOT NULL, base_ref text NOT NULL, policy_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE task_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES tasks(id), ordinal integer NOT NULL, kind text NOT NULL, status text NOT NULL, detail_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES tasks(id), status run_status NOT NULL, attempt integer NOT NULL, worker text NOT NULL, model text NOT NULL, worktree text, head_sha text, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE checkpoints (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES runs(id), stage text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES runs(id), kind text NOT NULL, status text NOT NULL, requested_at timestamptz NOT NULL, decided_at timestamptz, decided_by text, reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE model_calls (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES runs(id), provider text NOT NULL, model text NOT NULL, purpose text NOT NULL, input_tokens bigint NOT NULL, output_tokens bigint NOT NULL, cost_usd numeric(12,8) NOT NULL, metadata_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cost_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES runs(id), category text NOT NULL, amount_usd numeric(12,8) NOT NULL, metadata_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES runs(id), kind text NOT NULL, path text NOT NULL, sha256 text NOT NULL, metadata_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

